# Site settings
author: Dexter Fitch
title: Stumbling Building Blocks
header-img: img/home-bg.png
email: fitch.dexter@gmail.com
copyright_name: Dexter Fitch
description: > # this means to ignore newlines until "baseurl:"
  Platforming over learning hurdles
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dexterfitch

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
